# Generated by Django 4.2.1 on 2023-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolioModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('Url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
